# Generated by Django 4.0.5 on 2022-07-04 02:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.CharField(default='', max_length=20)),
                ('mes', models.CharField(default='', max_length=20)),
                ('diaInicio', models.CharField(default='', max_length=20)),
                ('diasMes', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoSalud',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('peso', models.IntegerField(default=0)),
                ('estatura', models.IntegerField(default=0)),
                ('probCardiaco', models.CharField(default='', max_length=100)),
                ('probPresion', models.CharField(default='', max_length=100)),
                ('movilidad', models.CharField(default='', max_length=100)),
                ('otrosPob', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='', max_length=100)),
                ('cuerpo', models.TextField(default='', max_length=1000)),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
                ('identificador', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(default='Publico/static/Publico/images/1.jpg', upload_to='Administrador')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('prioridad', models.CharField(default='', max_length=10)),
                ('esPublico', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fechaPago', models.DateField(default=datetime.datetime(2022, 7, 3, 22, 50, 10, 758022))),
                ('tipoPago', models.CharField(default='', max_length=20)),
                ('codigoTb', models.CharField(default='', max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('tipoDevolucion', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='', max_length=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(default='', max_length=100)),
                ('cuerpo', models.TextField(default='', max_length=1000)),
                ('estado', models.BooleanField(default=True)),
                ('correo', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(default='', max_length=100)),
                ('bajada', models.CharField(default='', max_length=400)),
                ('cuerpo', models.TextField(default='', max_length=1000)),
                ('imagen', models.ImageField(default='Publico/static/Publico/images/1.jpg', upload_to='Publico')),
                ('estado', models.BooleanField(default=True)),
                ('prioridad', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(default='', max_length=100)),
                ('cuerpo', models.TextField(default='', max_length=1000)),
                ('estado', models.BooleanField(default=True)),
                ('tipo', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='', max_length=100)),
                ('descripcion', models.CharField(default='', max_length=400)),
                ('dificultad', models.CharField(default='', max_length=10)),
                ('distancia', models.IntegerField(default=0)),
                ('tiempo', models.DurationField(default=datetime.timedelta)),
                ('urlMap', models.CharField(default='', max_length=200)),
                ('fechaActualizacion', models.DateField(default=datetime.datetime(2022, 7, 3, 22, 50, 10, 758022))),
                ('urlFoto', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('horaInicio', models.DateTimeField(default=datetime.datetime(2022, 7, 3, 22, 50, 10, 758022))),
                ('precio', models.IntegerField(default=0)),
                ('cupo', models.IntegerField(default=0)),
                ('cupoUsado', models.IntegerField(default=0)),
                ('cupoTraslado', models.IntegerField(default=0)),
                ('cupoTrasladoUsado', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('fecha', models.DateField(default=datetime.datetime(2022, 7, 3, 22, 50, 10, 758022))),
                ('lugarEncuentro', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(default='', max_length=200)),
                ('rut', models.CharField(default='', max_length=10)),
                ('nombres', models.CharField(default='', max_length=100)),
                ('apellidos', models.CharField(default='', max_length=100)),
                ('psw', models.CharField(default='', max_length=100)),
                ('nomUsuario', models.CharField(max_length=100)),
                ('celular', models.IntegerField(default=0)),
                ('contactoEmergencia', models.CharField(default='', max_length=100)),
                ('fonoEmergencia', models.IntegerField(default=0)),
                ('derivarA', models.CharField(default='', max_length=100)),
                ('fecNacimiento', models.DateField(default=datetime.datetime(2022, 7, 3, 22, 50, 10, 742290))),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
