# Generated by Django 4.0.5 on 2022-07-04 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_alter_galeria_imagen_alter_inscripcion_fechapago_and_more'),
        ('Administrador', '0011_alter_galeria_imagen_alter_inscripcion_fechapago_and_more'),
    ]

    operations = [
    ]
