# Generated by Django 4.0.5 on 2022-07-04 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0012_merge_20220703_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='imagen',
        ),
        migrations.AddField(
            model_name='galeria',
            name='esPublico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ruta',
            name='urlFoto',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fechaPago',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 23, 45, 34, 683170)),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='descripcion',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fechaActualizacion',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 23, 45, 34, 683170)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 23, 45, 34, 683170)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='horaInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 23, 45, 34, 683170)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecNacimiento',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 23, 45, 34, 683170)),
        ),
    ]
