# Generated by Django 4.0.5 on 2022-07-04 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0015_aviso_url_alter_inscripcion_fechapago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='imagen',
            field=models.ImageField(default=1, upload_to='Publico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fechaPago',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 3, 3, 8, 117829)),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fechaActualizacion',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 3, 3, 8, 101577)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 3, 3, 8, 117829)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='horaInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 3, 3, 8, 117687)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecNacimiento',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 3, 3, 8, 101577)),
        ),
    ]
