# Generated by Django 4.0.5 on 2022-07-04 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0016_ruta_imagen_alter_inscripcion_fechapago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fechaPago',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 3, 19, 8, 46015)),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='descripcion',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fechaActualizacion',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 3, 19, 8, 46015)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 3, 19, 8, 46015)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='horaInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 3, 19, 8, 46015)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecNacimiento',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 3, 19, 8, 30195)),
        ),
    ]
