# Generated by Django 4.0.5 on 2022-07-04 08:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0017_alter_inscripcion_fechapago_alter_ruta_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='imagen',
            field=models.ImageField(default='Publico/static/Publico/images/new/avatorNR', upload_to='Publico'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='imagen',
            field=models.ImageField(default='Publico/static/Publico/images/new/avatorNR', upload_to='Publico'),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='Administrador.mensaje'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fechaPago',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 4, 2, 47, 239645)),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='correo',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fechaActualizacion',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 4, 2, 47, 239645)),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='urlFoto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='urlMap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 4, 2, 47, 239645)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='horaInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 4, 2, 47, 239645)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecNacimiento',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 4, 2, 47, 239645)),
        ),
    ]
