# Generated by Django 4.0.5 on 2022-07-04 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0019_mensaje_usuario_respuesta_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fechaPago',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 5, 5, 8, 136848)),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='usuario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fechaActualizacion',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 5, 5, 8, 136848)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 5, 5, 8, 136848)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='horaInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 4, 5, 5, 8, 136848)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecNacimiento',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 5, 5, 8, 121214)),
        ),
    ]
