# Generated by Django 4.0.5 on 2022-07-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0003_estadosalud_delete_esadosalud_faq_cuerpo_faq_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='estadoPago',
        ),
        migrations.AddField(
            model_name='faq',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(default='Publico/static/Publico/images/1.jpg', upload_to='Administrador'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(default='Publico/static/Publico/images/1.jpg', upload_to='Publico'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salida',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
