# Generated by Django 4.0.5 on 2022-07-02 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0004_remove_inscripcion_estadopago_faq_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='identificador',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='fechaPago',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 11, 41, 27, 686788)),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='tipoDevolucion',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ruta',
            name='distancia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ruta',
            name='fechaActualizacion',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 11, 41, 27, 686788)),
        ),
        migrations.AddField(
            model_name='ruta',
            name='tiempo',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='salida',
            name='cupo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salida',
            name='cupoTraslado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salida',
            name='cupoTrasladoUsado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salida',
            name='cupoUsado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 11, 41, 27, 686788)),
        ),
        migrations.AddField(
            model_name='salida',
            name='horaInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 11, 41, 27, 686788)),
        ),
        migrations.AddField(
            model_name='salida',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecNacimiento',
            field=models.DateField(default=datetime.datetime(2022, 7, 2, 11, 41, 27, 686788)),
        ),
        migrations.AlterField(
            model_name='estadosalud',
            name='estatura',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estadosalud',
            name='peso',
            field=models.IntegerField(default=0),
        ),
    ]
