# Generated by Django 4.0.5 on 2022-07-03 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0009_alter_galeria_url_alter_inscripcion_fechapago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='imagen',
            field=models.ImageField(default='Publico/static/Publico//services/cerro-manquehito.jpg', upload_to='Administrador'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fechaPago',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 1, 15, 44, 753205)),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fechaActualizacion',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 1, 15, 44, 753205)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 1, 15, 44, 753205)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='horaInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 1, 15, 44, 753205)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecNacimiento',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 1, 15, 44, 744624)),
        ),
    ]
