# Generated by Django 4.0.5 on 2022-07-03 08:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0010_ruta_imagen_alter_inscripcion_fechapago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fechaPago',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 4, 51, 5, 248180)),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='fechaActualizacion',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 4, 51, 5, 248180)),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='imagen',
            field=models.ImageField(default='Publico/static/Publico/services/imaes/cerro-manquehito.jpg', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 4, 51, 5, 248180)),
        ),
        migrations.AlterField(
            model_name='salida',
            name='horaInicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 3, 4, 51, 5, 248180)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecNacimiento',
            field=models.DateField(default=datetime.datetime(2022, 7, 3, 4, 51, 5, 244092)),
        ),
    ]
