# Generated by Django 4.0.5 on 2022-06-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTrekking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen_galeria',
            name='imagen',
            field=models.ImageField(upload_to='gestionTrekking'),
        ),
    ]
