# Generated by Django 4.0.5 on 2022-06-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTrekking', '0002_alter_imagen_galeria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen_galeria',
            name='imagen',
            field=models.ImageField(upload_to='media'),
        ),
    ]
