# Generated by Django 4.0.5 on 2022-06-28 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTrekking', '0003_alter_imagen_galeria_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen_galeria',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagen_galeria',
            name='lugar',
            field=models.CharField(default='cerro campanita', max_length=50),
            preserve_default=False,
        ),
    ]
