# Generated by Django 4.0.5 on 2022-06-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTrekking', '0004_imagen_galeria_fecha_imagen_galeria_lugar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='media')),
                ('texto', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='imagen_galeria',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
