# Generated by Django 4.0.5 on 2022-06-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTrekking', '0005_banner_alter_imagen_galeria_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('bajada', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(upload_to='media')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('prioridad', models.CharField(max_length=10)),
            ],
        ),
    ]
