# Generated by Django 4.0.5 on 2022-06-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTrekking', '0006_faq_noticias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateField()),
                ('favicon', models.ImageField(upload_to='media')),
                ('logo1', models.ImageField(upload_to='media')),
                ('logo2', models.ImageField(upload_to='media')),
                ('logo3', models.ImageField(upload_to='media')),
            ],
        ),
    ]
