# Generated by Django 4.0.5 on 2022-06-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionTrekking', '0007_plantilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('slide', models.ImageField(upload_to='media')),
            ],
        ),
    ]
